item:
  texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjRkMWVkZGVhYzgzMGQ5ZGVhMTJiODg4OTk3YjI4OWZhODRiNjljOTAxZjJjNTc0NGFmOTc1ZmM0OTRlYmUzIn19fQ=="
  name: "&6&lCarved Pumpkin &e#<number>"
  lore:
    - "&8Trick or Treat?!"
    - ""
    - "&7This Carved Pumpkin was number &e<number> &7ever found!"
    - "&7Found by: &e<founder>&7."
    - "&7"
    - "&7&6■ &eDeliver it to the witch in spawn"
    - ""
    - "&5&m                             "
    - "&6&lRelic Item"
    - "&fTier: &5Utility"
    - "&5&m                             "
    - ""
    - "&c☠ Happy Halloween!"

excluded-blocks:
  - SNOW

rates:
  block-break: 0.005
  block-place: 0.008
  mob-kill: 0.04

broadcast:
  title:
    fade-in: 1
    stay: 2
    fade-out: 1
    title: "&c☠ &6You found a Carved Pumpkin! &c☠"
    subtitle: "&7Return it to the witch in spawn."
  sound: "ENTITY_PLAYER_LEVELUP"
  broadcast-msg: "&6&lPumpkinCarver &8» &e<player> &7found &6Pumpkin #<number>&7!"

redeem:
  npc-id: 27
  title:
    fade-in: 1
    stay: 2
    fade-out: 1
    title: "&c☠ &6Thank You! &c☠"
    subtitle: "&eOpen Jacky the Lantern."
  sound: "ENTITY_WITCH_CELEBRATE"
  message: "&6&lPumpkinCarver &8» &eYou can now open Jacky the Lantern."
  console-command: "treasures keys <player> halloweenfree add 1"

elf:
  npc-id: 64
  console-command: "md give custom <player> PumpkinPie 1"

messages:
  pumpkins: "&6&lPumpkinCarver &8» &7A total of &6#<number> Pumpkins &7have dropped!"
  pumpkins-drop: "&6&lPumpkinCarver &8» &e<player> &7dropped &6&lPumpkin #<number>&7 in spawn!"
  pumpkins-give: "&6&lPumpkinCarver &8» &7Gave &6Pumpkin #<number> to &e<player>&7"
  reload: "&6&lInfo &8» &7You reloaded PumpkinCarver."
