item:
  texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjRkMWVkZGVhYzgzMGQ5ZGVhMTJiODg4OTk3YjI4OWZhODRiNjljOTAxZjJjNTc0NGFmOTc1ZmM0OTRlYmUzIn19fQ=="
  name: "&6Carved Pumpkin %GlobalPumpkinCounter%"
  lore:
    - "&7Trick or treat?"
    - "&7Find out at /spawn"

excluded-blocks:
  - SNOW

rates:
  block-break: 0.005
  block-place: 0.008
  mob-kill: 0.04

broadcast:
  title:
    fade-in: 1
    stay: 4
    fade-out: 1
    title: "&6☠ &eYou found a Carved Pumpkin! &6☠"
    subtitle: ""
  sound: "ENTITY_PLAYER_LEVELUP"
  broadcast-msg: "&6&lPumpkinCarver &8» &e<player> &7found &6Pumpkin #<number>&7!"

redeem: # todo
  npc-id: 3
  title:
    fade-in: 1
    stay: 4
    fade-out: 1
    title: ""
    subtitle: ""
  message: ""
  console-command: ""

messages:
  pumpkins: "&6&lPumpkinCarver &8» &7A total of &6<GlobalPumpkinCounter> Pumpkins &7have dropped!"
  pumpkins-drop: "&6&lPumpkinCarver &8» &e<player> &7dropped &6&lPumpkin #<GlobalPumpkinCounter>&7 in spawn!"
  pumpkins-give: "&6&lPumpkinCarver &8» &7Gave &6Pumpkin #<number> to &e<player>&7"
  reload: "&6&lInfo &8» &7You reloaded PumpkinCarver."
